-- ============================================================
-- Add missing risk_events table and update alerts table types
-- ============================================================

-- ── Risk Events ─────────────────────────────────────────────────────────────────────
-- Burnout risk events (generated by prediction service)
create table risk_events (
   id              uuid primary key default uuid_generate_v4(),
   user_id         uuid not null references users(id) on delete cascade,
   org_id          uuid not null references organizations(id) on delete cascade,
   risk_level      text not null check (risk_level in ('low','medium','high','critical')),
   predicted_burnout_date date,   -- ML prediction
   contributing_factors jsonb,
   acknowledged_by uuid references users(id) on delete set null,
   created_at      timestamptz not null default now()
);

create index risk_events_user_id_idx on risk_events(user_id);
create index risk_events_org_id_idx on risk_events(org_id);
create index risk_events_created_at_idx on risk_events(created_at desc);

-- Enable RLS on risk_events
alter table risk_events enable row level security;

-- RLS policies for risk_events
create policy "risk_events_org_managers" on risk_events
   for select using (
     org_id = (select org_id from users where id = auth.uid()) and
     (select role from users where id = auth.uid()) in ('manager', 'hr', 'admin')
   );

create policy "risk_events_insert_any" on risk_events
   for insert with check (true);  -- Service role only should insert

-- ── Alerts ────────────────────────────────────────────────────────────────────────
-- Update alert types to match PLAN.md
-- First, drop the old check constraint
alter table alerts
   drop constraint if exists alerts_type_check;

-- Add new check constraint with correct types
alter table alerts
   add constraint alerts_type_check
   check (type in (
                 'team_risk_spike',
                 'individual_high_risk',
                 'trend_alert'
               ));