-- ============================================================
-- Resylia schema updates v2
-- Adds missing tables and columns to align with PLAN.md
-- ============================================================

-- ── Risk Events Table (missing from original schema) ─────────────────────────────────────
-- Stores burnout risk events generated by the prediction service
create table risk_events (
  id                      uuid primary key default uuid_generate_v4(),
  user_id                 uuid not null references users(id) on delete cascade,
  org_id                  uuid not null references organizations(id) on delete cascade,
  risk_level              text not null check (risk_level in ('low','medium','high','critical')),
  predicted_burnout_date  date,
  contributing_factors    jsonb,
  acknowledged_by         uuid references users(id) on delete set null,
  created_at              timestamptz not null default now()
);

-- Indexes for risk_events
create index risk_events_user_id_idx         on risk_events(user_id);
create index risk_events_org_id_idx          on risk_events(org_id);
create index risk_events_created_at_idx      on risk_events(created_at desc);
create index risk_events_risk_level_idx      on risk_events(risk_level);

-- ── Organizations: Add missing columns ───────────────────────────────────────────────────
alter table organizations
  add column if not exists domain text unique,
  add column if not exists encryption_key text,
  add column if not exists subscription_tier text default 'starter',
  add column if not exists subscription_status text default 'active',
  add column if not exists trial_started_at timestamptz,
  add column if not exists trial_ends_at timestamptz,
  add column if not exists razorpay_customer_id text;

-- ── Users: Add missing columns ───────────────────────────────────────────────────────────
alter table users
  add column if not exists custom_persona text,
  add column if not exists two_factor_secret text,
  add column if not exists two_factor_enabled boolean default false,
  add column if not exists two_factor_verified boolean default false;

-- ── Alerts: Update alert types to match PLAN.md ──────────────────────────────────────────
-- First, check if we need to modify the constraint
-- We'll drop the old constraint and add a new one
alter table alerts
  drop constraint if exists alerts_type_check,
  add constraint alerts_type_check
    check (type in (
      'team_risk_spike',
      'individual_high_risk',
      'trend_alert'
    ));

-- Enable RLS on new tables
alter table risk_events enable row level security;

-- ── RLS Policies for new tables ────────────────────────────────────────────────────────

-- Risk events: only viewable by managers/HR within same org
create policy "risk_events_org_managers" on risk_events
  for select using (
    org_id = (select org_id from users where id = auth.uid()) and
    (select role from users where id = auth.uid()) in ('manager', 'hr', 'admin')
  );

-- Risk events: insertable by service role/prediction service only
-- (We'll rely on application layer security for inserts since this isML-generated data)

-- ── Updated policies for organizations with new columns ───────────────────────────────────
-- No changes needed to existing policies as they're based on org_id and role

-- ── Updated policies for users with new columns ───────────────────────────────────────────
-- No changes needed to existing policies as they're based on org_id and role