-- ============================================================
-- Resylia schema v1
-- Run: supabase db reset   (development)
--      supabase db push     (production)
-- ============================================================

-- Extensions
create extension if not exists "uuid-ossp";
create extension if not exists "pg_cron";        -- for scheduled alert jobs

-- ── Organizations ─────────────────────────────────────────────────────────────
create table organizations (
  id                  uuid primary key default uuid_generate_v4(),
  name                text not null check (length(name) between 2 and 100),
  slug                text not null unique check (slug ~ '^[a-z0-9\-]+$'),
  plan                text not null default 'starter' check (plan in ('starter','growth','enterprise')),
  seat_count          int  not null default 10 check (seat_count > 0),
  stripe_customer_id  text unique,
  slack_team_id       text unique,
  created_at          timestamptz not null default now()
);

-- ── Users ─────────────────────────────────────────────────────────────────────
create table users (
  id              uuid primary key references auth.users(id) on delete cascade,
  org_id          uuid not null references organizations(id) on delete cascade,
  role            text not null default 'employee'
                    check (role in ('employee','manager','hr','admin')),
  department      text,
  manager_id      uuid references users(id) on delete set null,
  slack_user_id   text unique,
  slack_tz_offset int default 0,  -- seconds from UTC
  is_active       boolean not null default true,
  created_at      timestamptz not null default now()
);

create index users_org_id_idx       on users(org_id);
create index users_manager_id_idx   on users(manager_id);
create index users_slack_user_id_idx on users(slack_user_id) where slack_user_id is not null;

-- ── Subscriptions ─────────────────────────────────────────────────────────────
create table subscriptions (
  id                      uuid primary key default uuid_generate_v4(),
  org_id                  uuid not null unique references organizations(id) on delete cascade,
  stripe_subscription_id  text unique,
  status                  text not null default 'trialing'
                            check (status in ('trialing','active','past_due','canceled','unpaid')),
  plan                    text not null default 'starter',
  seat_count              int  not null default 10,
  current_period_end      timestamptz,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

-- ── Check-ins ─────────────────────────────────────────────────────────────────
create table checkins (
  id                  uuid primary key default uuid_generate_v4(),
  user_id             uuid not null references users(id) on delete cascade,
  org_id              uuid not null references organizations(id) on delete cascade,
  energy              int  not null check (energy between 1 and 5),
  stress              int  not null check (stress between 1 and 5),
  workload            int  not null check (workload between 1 and 5),
  -- free_text stored encrypted; never returned to managers or AI coach
  free_text           text check (length(free_text) <= 500),
  sentiment_score     real check (sentiment_score between -1.0 and 1.0),
  burnout_risk_score  real check (burnout_risk_score between 0.0 and 1.0),
  source              text not null default 'web'
                        check (source in ('web','slack','teams')),
  checked_in_at       timestamptz not null default now()
);

-- Unique: one check-in per user per calendar day
create unique index checkins_one_per_day_idx
  on checkins(user_id, date_trunc('day', checked_in_at at time zone 'utc'));

create index checkins_user_id_idx         on checkins(user_id);
create index checkins_org_id_idx          on checkins(org_id);
create index checkins_checked_in_at_idx   on checkins(checked_in_at desc);

-- ── Alerts ────────────────────────────────────────────────────────────────────
-- Generated by the risk engine — NEVER contain individual user references
create table alerts (
  id          uuid primary key default uuid_generate_v4(),
  org_id      uuid not null references organizations(id) on delete cascade,
  manager_id  uuid references users(id) on delete set null,
  type        text not null check (type in (
                'team_avg_stress_high',
                'team_participation_drop',
                'team_energy_declining',
                'workload_spike'
              )),
  payload     jsonb not null default '{}',   -- aggregated data only, no user ids
  seen_at     timestamptz,
  created_at  timestamptz not null default now()
);

create index alerts_org_manager_idx on alerts(org_id, manager_id, seen_at nulls first);

-- ── Audit log ─────────────────────────────────────────────────────────────────
create table audit_log (
  id          uuid primary key default uuid_generate_v4(),
  event       text not null,
  user_id     uuid references users(id) on delete set null,
  ip          text,
  context     jsonb not null default '{}',
  created_at  timestamptz not null default now()
);

create index audit_log_event_idx      on audit_log(event);
create index audit_log_user_id_idx    on audit_log(user_id) where user_id is not null;
create index audit_log_created_at_idx on audit_log(created_at desc);

-- Retention: auto-delete audit logs older than 2 years
select cron.schedule(
  'audit_log_retention',
  '0 3 * * *',
  $$delete from audit_log where created_at < now() - interval '2 years'$$
);

-- ── Slack action queue ────────────────────────────────────────────────────────
create table slack_action_queue (
  id                uuid primary key default uuid_generate_v4(),
  slack_user_id     text not null,
  resylia_user_id   uuid references users(id) on delete cascade,
  org_id            uuid references organizations(id) on delete cascade,
  action_id         text not null,
  value             text,
  processed_at      timestamptz,
  created_at        timestamptz not null default now()
);

create index slack_queue_pending_idx on slack_action_queue(created_at) where processed_at is null;
